// @refresh reload
import "./root.css";
import { Suspense, VoidComponent } from "solid-js";
import {
  A,
  Body,
  ErrorBoundary,
  FileRoutes,
  Head,
  Html,
  Meta,
  Routes,
  Scripts,
  Title,
  Link,
} from "solid-start";
import { SessionProvider } from "@solid-auth/base/client";
import { QueryProvider } from "@prpc/solid";
import { QueryClient } from "@tanstack/solid-query";

const queryClient = new QueryClient();

const SiteNav: VoidComponent = () => (
  <header>
    <nav>
      <ul class="mx-auto flex w-[min(80%,44rem)] items-center justify-around gap-10 py-5">
        <li class="text-lg hover:underline">
          <A href="/">Home</A>
        </li>
        <li class="text-lg hover:underline">
          <A href="/game">Game</A>
        </li>
        <li class="text-lg hover:underline">
          <A href="/deck">Deck</A>
        </li>
        <li class="text-lg hover:underline">
          <A href="/drag">Drag</A>
        </li>
        <li class="text-lg hover:underline">
          <A href="/test">Test</A>
        </li>
      </ul>
    </nav>
  </header>
);

export default function Root() {
  return (
    <Html lang="en">
      <Head>
        <Title>SwingOut</Title>
        <Meta charset="utf-8" />
        <Meta name="viewport" content="width=device-width, initial-scale=1" />
        <Meta name="theme-color" content="#026d56" />
        <Meta name="description" content="Generated by create-jd-app" />
        <Link rel="icon" href="/favicon.ico" />
      </Head>
      <Body class="grid min-h-screen grid-rows-[auto_1fr] bg-sand2 text-sand12">
        <QueryProvider queryClient={queryClient}>
          <SessionProvider>
            <Suspense>
              <ErrorBoundary>
                <SiteNav />
                <Routes>
                  <FileRoutes />
                </Routes>
              </ErrorBoundary>
            </Suspense>
          </SessionProvider>
        </QueryProvider>
        <Scripts />
      </Body>
    </Html>
  );
}
